services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=danicustodio
      - POSTGRESQL_PASSWORD=techdeveloper
      - POSTGRESQL_DATABASE=brevly
    volumes:
      - postgres_data:/bitnami/postgresql
      - './docker:/docker-entrypoint-initdb.d'

  server:
    build: .
    depends_on:
      - pg
    environment:
      - NODE_ENV=production
      - PORT=3333
      - BREVLY_BASE_URL=http://localhost:5173
      - DATABASE_URL=postgresql://danicustodio:techdeveloper@pg:5432/brevly
      - CLOUDFLARE_ACCOUNT_ID=
      - CLOUDFLARE_ACCESS_KEY_ID=
      - CLOUDFLARE_SECRET_ACCESS_KEY=
      - CLOUDFLARE_BUCKET=
      - CLOUDFLARE_PUBLIC_URL=
    ports:
      - '3333:3333'
    restart: unless-stopped

volumes:
  postgres_data:
    name: brevly-postgres-data
